import { WindowOption } from './windowOption';

const userPermittedWindowOptions: Array<keyof WindowOption> = [
    'accelerator',
    'alphaMask',
    'alwaysOnTop',
    'api',
    'applicationIcon',
    'aspectRatio',
    'autoShow',
    'backgroundColor',
    'contentNavigation',
    'contextMenu',
    'contextMenuSettings',
    'cornerRounding',
    'customData',
    'customRequestHeaders',
    'defaultCentered',
    'defaultHeight',
    'defaultLeft',
    'defaultTop',
    'defaultWidth',
    'frame',
    'hideOnClose',
    'icon',
    'maxHeight',
    'maximizable',
    'maxWidth',
    'minHeight',
    'minimizable',
    'minWidth',
    'name',
    'opacity',
    'preloadScripts',
    'resizable',
    'resizeRegion',
    'saveWindowState',
    'shadow',
    'showTaskbarIcon',
    'smallWindow',
    'state',
    'taskbarIconGroup',
    'transparent',
    'url',
    'uuid',
    'waitForPageLoad',
];

export default userPermittedWindowOptions;